### ISSUE TITLE
Most Popular Movies Demo isn't working

### ISSUE THREAD

**Issue by thesohelshaikh** [cavestri/themoviedb-javascript-library#46]
- There is no search button.
- Pressing enter also doesn't seem to work.

**Comment by cavestri** [comment]
Hi, that website is an example of how to use library, I'm not the owner of that site, the owner is: @abdulhannanali and apparently the idea is get a list of the most popular movies (listed below the filtering field) without search capability.

Greetings!

**Comment by thesohelshaikh** [comment]
Okay, so maybe remove the demo link?

**Comment by abdulhannanali** [comment]
@thesohelshaikh The demo still works fine for me. It's a basic demo. The demo gets a list of popular movies using the api, and the text bar there is to filter as @cavestri explained. It sadly doesn't have a search functionality. 

I suggest that it shouldn't be removed since it still demonstrates the usage of this very specific library @cavestri created but it's totally up to him to make the final call :

**Comment by abdulhannanali** [comment]
Pretty surprised it still works fine, since I made it years ago and when I was just starting to code :laughing:

**Comment by thesohelshaikh** [comment]
I am sorry it didn’t work for me the first time. Also i was trying to search. My bad. 😒
